### ISSUE TITLE
Will this work with UE5

### ISSUE THREAD

**Issue by lonnietc** [yas-online/UE4-DedicatedServer#13]
Hello,

I am exploring Unreal Engine 5 and also the possibility of external dedicated servers as well.

Just wondering if this will work with the latest engine also?

**Comment by neico** [comment]
I have no idea, I didn't even have time (or the disk space) to install UE5 yet.
I'd wager that the answer is no.

**Comment by lonnietc** [comment]
Yea, UE5 is big and I have just started playing around with it as well.

It seems to have some very nice features from what I have seen in the videos, but I am still a beginner with it and am more on the coding and development side of things.

Thanks again.
