### ISSUE TITLE
Incompatible with 4.18+

### ISSUE THREAD

**Issue by HiIAmMoot** [yas-online/UE4-DedicatedServer#3]
As of 4.18, the following includes were removed:
"Private/Windows/WindowsPlatformOutputDevicesPrivate.h"
"Private/Mac/MacPlatformOutputDevicesPrivate.h"
"Private/Linux/LinuxPlatformOutputDevicesPrivate.h"

I do not know what replaced them though. These includes are used in ServerConsole.h

**Comment by neico** [comment]
Those headers were moved from "Private" to "Public" in 4.18, meaning that you can just remove the `Private` part of those and change [Source/DedicatedServer/DedicatedServer.Build.cs#L14](https://github.com/yas-online/UE4-DedicatedServer/blob/master/Source/DedicatedServer/DedicatedServer.Build.cs#L14) to look like this: `PrivateDependencyModuleNames.AddRange( new string[] {  } );`

Of course you'll probably need to change a bit more than that as the engine simplified and moved things around quite a bit, but I can't quite locate all the needed parts without actually compiling and looking what errors it returns right now.

I'm busy with a lot of other stuff currently, but will try to get this plugin updated with all the new changes as soon as I'm able to.

Also: see this fork's commit for an idea what do do: https://github.com/TheTrueBander/UE4-DedicatedServerUtils/commit/5634e9a80d09263127a008a3833600318be870fa

**Comment by Scienziatogm** [comment]
> Those headers were moved from "Private" to "Public" in 4.18, meaning that you can just remove the `Private` part of those and change [Source/DedicatedServer/DedicatedServer.Build.cs#L14](https://github.com/yas-online/UE4-DedicatedServer/blob/master/Source/DedicatedServer/DedicatedServer.Build.cs#L14) to look like this: `PrivateDependencyModuleNames.AddRange( new string[] { } );`
> 
> Of course you'll probably need to change a bit more than that as the engine simplified and moved things around quite a bit, but I can't quite locate all the needed parts without actually compiling and looking what errors it returns right now.
> 
> I'm busy with a lot of other stuff currently, but will try to get this plugin updated with all the new changes as soon as I'm able to.
> 
> Also: see this fork's commit for an idea what do do: https://github.com/TheTrueBander/UE4-DedicatedServerUtils/commit/5634e9a80d09263127a008a3833600318be870fa

The fork's commit is not available. I'm using 4.22.3 and I'm getting lots of errors.

**Comment by neico** [comment]
I can imagine, if I only would finally get the time to focus on the stuff I like,
fixing this project up and get the stuff done I planned for it has been something I really want to do,
yet I don't even have any recent UE4 version installed because time constrains don't even allow me to take a look at what's happening on UE4 recently...

At some point I was even wondering if this plugin is even still needed and if Epic Games fixed it themselves by now, I guess your response can be counted as that they didn't?

I guess if someone is willing to provide a PR I can spare some time to review and merge it tough, it's probably better than waiting for me to find a proper time frame (which might not come before next year looking as things stands)

**Comment by Scienziatogm** [comment]
> I can imagine, if I only would finally get the time to focus on the stuff I like,
> fixing this project up and get the stuff done I planned for it has been something I really want to do,
> yet I don't even have any recent UE4 version installed because time constrains don't even allow me to take a look at what's happening on UE4 recently...
> 
> At some point I was even wondering if this plugin is even still needed and if Epic Games fixed it themselves by now, I guess your response can be counted as that they didn't?
> 
> I guess if someone is willing to provide a PR I can spare some time to review and merge it tough, it's probably better than waiting for me to find a proper time frame (which might not come before next year looking as things stands)

Thank you for your patience and your answer! Maybe I found a way to proper compile your plugin without errors on the latest UE4 version. Now I'll test it and if it works, I'll make a pull request.

I'm working on the Exec game thread issue too

**Comment by neico** [comment]
Should be fixed with https://github.com/yas-online/UE4-DedicatedServer/commit/9eca9af70c816be6453267ef83f8986845f9bb32
Not sure if it also retroactively fixed older branches tough.
