### ISSUE TITLE
4.23 compatibility

### ISSUE THREAD

**Issue by fillmoreb** [yas-online/UE4-DedicatedServer#6]
In DedicatedServer.cpp the signature of Async has changed.  Call type is now inferred.  changing `Async<void>` to `Async<>` allowed the compilation of the plugin.  I don't want to make a pull request because I don't know how or if this change would affect earlier versions of the engine.

Related conversation: https://forums.unrealengine.com/development-discussion/c-gameplay-programming/1650841-async-call-with-calltype

**Comment by neico** [comment]
Generally I'm favoring latest stable over older versions, there's a change history for those that need an older build.
If it works, feel free to make a PR.

**Comment by fillmoreb** [comment]
Created.
